# Generated by Django 4.2.5 on 2023-10-25 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emprestimo",
            old_name="dia",
            new_name="final",
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="contato",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="inicio",
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
