# Generated by Django 4.2.3 on 2023-07-04 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="descricao",
            new_name="titulo",
        ),
    ]
