# Generated by Django 4.2.5 on 2023-11-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0002_rename_dia_emprestimo_final_emprestimo_contato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="nome_livro",
            field=models.ForeignKey(                
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emprestimos",
                blank=True,
                null=True,
                to="livraria.livro",
            ),
            preserve_default=False,
        ),
    ]
