# Generated by Django 4.2.5 on 2023-11-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0004_remove_emprestimo_nome_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="nome_livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emprestimos",
                to="livraria.livro",
                blank=True,
                null=True,
            ),
            preserve_default=False,
        ),
    ]
