# Generated by Django 4.2.3 on 2023-08-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0005_livro_capa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="categoria",
        ),
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ManyToManyField(
                related_name="livros", to="livraria.categoria"
            ),
        ),
    ]
