# Generated by Django 4.2.4 on 2023-09-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0007_autor_editora_remove_livro_autores_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localização",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("telefone", models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AddField(
            model_name="livro",
            name="devolucao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livro",
            name="emprestimo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="livro",
            name="editora",
        ),
        migrations.AlterField(
            model_name="livro",
            name="isbn",
            field=models.DecimalField(decimal_places=0, default=1, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livro",
            name="localizacao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="livraria.localização",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livro",
            name="editora",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="livraria.editora",
            ),
            preserve_default=False,
        ),
    ]
